import * as pdfjsLib from 'pdfjs-dist'
import { markRaw } from 'vue'
import { EventBus, PDFFindController, PDFLinkService, PDFViewer } from 'pdfjs-dist/web/pdf_viewer.mjs'
import workerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url'
import { viewerState } from '../stores/viewerState'
import { revokeDesktopFile, setCurrentGrant } from './native'
import type { PdfSource } from '../types/pdf'
pdfjsLib.GlobalWorkerOptions.workerSrc = workerUrl
const zoomLevels = [0.5, .67, .75, .8, .9, 1, 1.1, 1.25, 1.5, 1.75, 2, 2.5, 3]
export class PdfViewerController {
  private viewer!: PDFViewer; private linkService!: PDFLinkService; private findController!: PDFFindController; private eventBus!: EventBus; private loadingTask: any; private source: PdfSource | null = null; private generation = 0
  init(container: HTMLDivElement, element: HTMLDivElement) { const eventBus = this.eventBus = new EventBus(); this.linkService = new PDFLinkService({ eventBus }); this.findController = new PDFFindController({ linkService: this.linkService, eventBus }); this.viewer = new PDFViewer({ container, viewer: element, eventBus, linkService: this.linkService, findController: this.findController, textLayerMode: 1 }); this.linkService.setViewer(this.viewer); eventBus.on('pagesinit', () => { this.viewer.currentScaleValue = 'page-width' }); eventBus.on('pagechanging', (e: any) => { viewerState.pageNumber = e.pageNumber }); eventBus.on('scalechanging', (e: any) => { if (typeof e.scale === 'number') viewerState.scale = e.scale }); eventBus.on('updatefindmatchescount', (e: any) => { viewerState.searchCurrent = e.matchesCount.current; viewerState.searchTotal = e.matchesCount.total }) }
  async open(source: PdfSource) { await this.close(); const id = ++this.generation; viewerState.loading = true; viewerState.error = null; try { this.source = source; setCurrentGrant(source.kind === 'url' ? source.grantId : undefined); this.loadingTask = pdfjsLib.getDocument(source.kind === 'url' ? { url: source.url } : { data: source.data }); this.loadingTask.onPassword = (update: (password: string) => void) => { const password = window.prompt('请输入 PDF 密码'); if (password !== null) update(password); else void this.loadingTask.destroy() }; const pdf = await this.loadingTask.promise; if (id !== this.generation) { await pdf.destroy(); return }; this.viewer.setDocument(pdf); this.linkService.setDocument(pdf); this.findController.setDocument(pdf); viewerState.document = markRaw(pdf); viewerState.documentName = source.name; viewerState.pageCount = pdf.numPages; viewerState.pageNumber = 1; try { viewerState.outline = (await pdf.getOutline() ?? []) as any } catch { viewerState.outline = [] } } catch (error: any) { console.error('PDF load failed', error); if (id === this.generation && error?.name !== 'AbortException') { const reason = typeof error?.message === 'string' ? `（${error.message}）` : ''; viewerState.error = error?.name === 'PasswordException' ? '需要正确的 PDF 密码。' : `无法读取该 PDF，文件可能已损坏或授权已失效。${reason}` } } finally { if (id === this.generation) viewerState.loading = false } }
  async close() { this.generation++; (this.viewer as any)?.setDocument(null); (this.linkService as any)?.setDocument(null); (this.findController as any)?.setDocument(null); if (this.loadingTask) { try { await this.loadingTask.destroy() } catch {} this.loadingTask = null }; if (this.source?.kind === 'url') await revokeDesktopFile(this.source.grantId); this.source = null; viewerState.document = null; viewerState.pageCount = 0; viewerState.outline = []; viewerState.searchQuery = ''; viewerState.searchCurrent = 0; viewerState.searchTotal = 0 }
  setPage(page: number) { if (this.viewer) this.viewer.currentPageNumber = Math.min(Math.max(Math.round(page) || 1, 1), viewerState.pageCount || 1) }; nextPage() { this.setPage(viewerState.pageNumber + 1) }; previousPage() { this.setPage(viewerState.pageNumber - 1) }; setScale(scale: number | string) { if (this.viewer) this.viewer.currentScaleValue = String(scale) }; zoomIn() { this.setScale(zoomLevels.find(v => v > viewerState.scale + .001) ?? 3) }; zoomOut() { this.setScale([...zoomLevels].reverse().find(v => v < viewerState.scale - .001) ?? .5) }; fitWidth() { this.setScale('page-width') }; fitPage() { this.setScale('page-fit') }; find(query: string, previous = false) { viewerState.searchQuery = query; this.eventBus.dispatch('find', { source: this, type: '', query, phraseSearch: true, highlightAll: true, findPrevious: previous } as any) }; goToDestination(dest: any) { this.linkService.goToDestination(dest) }
}
