<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { desktop, type FileAssociationStatus } from '../services/desktop'
const emit = defineEmits<{ close: [] }>(); const info = ref<FileAssociationStatus | null>(null); const busy = ref(false); const error = ref('')
const stateLabel = computed(() => !info.value ? '正在检查' : info.value.current ? '已注册' : info.value.registered ? '需要修复' : '未注册')
async function refresh() { error.value = ''; try { info.value = await desktop.association.status() } catch (cause) { error.value = cause instanceof Error ? cause.message : '无法读取 Windows 集成状态。' } }
async function update(action: 'register' | 'unregister') { if (busy.value) return; busy.value = true; error.value = ''; try { await desktop.association[action](); await refresh() } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Windows 集成操作失败。' } finally { busy.value = false } }
async function openDefaultApps() { try { await desktop.association.openDefaultApps() } catch (cause) { error.value = cause instanceof Error ? cause.message : '无法打开默认应用设置。' } }
onMounted(() => { void refresh() })
</script>
<template><div class="dialog-backdrop" @mousedown.self="!busy && emit('close')"><section class="dialog integration-dialog" role="dialog" aria-modal="true" aria-labelledby="integration-title"><button class="dialog-close" aria-label="关闭" :disabled="busy" @click="emit('close')">×</button><div class="integration-heading"><div><h2 id="integration-title">Windows 集成</h2><p>让 PDF 文件更方便地使用 lw.PDF 打开。</p></div><span class="integration-status" :class="{ current: info?.current, repair: info?.registered && !info?.current }">{{ stateLabel }}</span></div><ul><li>右键菜单显示“使用 lw.PDF 打开”</li><li>Windows“打开方式”显示 lw.PDF</li><li>支持 .pdf 文件关联</li></ul><p class="integration-note">注册不会修改当前默认 PDF 应用。如需默认使用 lw.PDF，请在 Windows 设置中自行选择。</p><div v-if="info?.registered && !info.current" class="path-warning"><strong>检测到程序位置发生变化</strong><span :title="info.registeredExecutablePath || ''">{{ info.registeredExecutablePath || '原注册路径不可用' }}</span></div><p v-if="error" class="dialog-error">{{ error }}</p><div class="dialog-actions"><button :disabled="!info?.current || busy" @click="openDefaultApps">默认应用设置…</button><span class="dialog-spacer"/><button v-if="info?.registered" :disabled="busy" @click="update('unregister')">取消注册</button><button v-if="!info?.current" class="primary" :disabled="!info || busy" @click="update('register')">{{ busy ? '正在处理…' : info?.registered ? '修复关联' : '注册 Windows 集成' }}</button><button :disabled="busy" @click="emit('close')">完成</button></div></section></div></template>
